version: '3.4'

services:
  app-development:
    container_name: jasongallagher_app-dev
    image: jasongallagher_app:dev
    command: ["npm", "start"]
    volumes:
      - './app:/src/app'
      - './server:/src/server'
      - './config:/src/config'
      - './package.json:/src/package.json'
      # - './package-lock.json:/src/package-lock.json'
      - './webpack.config.js:/src/webpack.config.js'
      - './webpack.production.config.js:/src/webpack.production.config.js'
      - './.babelrc:/src/.babelrc'
      - './.eslintrc:/src/.eslintrc'
      - './postcss.config.js:/src/postcss.config.js'
      - './setupTests.js:/src/setupTests.js'
      - './public:/src/public'
      - './coverage:/src/coverage'
    ports:
      - '3200:3200' # app
      - '8888:8888' # webpack-bundle-analyzer
    env_file:
      - ./secrets/.env.staging
    environment:
      - NODE_ENV=development
    restart: 'always'
    depends_on:
      - db-staging
